services:
  gateway:
    image: gateway_image
    build:
      context: ./gateway_service
    ports:
      - "8000:8000"
    depends_on:
      - auth_service
      - question_service

  auth_service:
    image: auth_service_image
    env_file:
      - ./auth_service/.env
    build:
      context: ./auth_service
    ports:
      - "8001:8001"
    depends_on:
      - mongo

  question_service:
    image: question_service_image
    env_file:
      - ./question_service/.env
    build:
      context: ./question_service
    ports:
      - "8002:8002"

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "3000:80"
    depends_on:
      - gateway

volumes:
  mongo_data:
