services:
  gateway:
    image: gateway_image
    build:
      context: ./gateway_service
    ports:
      - "8000:8000"
#    deploy:
#      replicas: 2 #Done for test of two services running
    depends_on:
      - auth_service
      - question_service
      - questions_history_service
    networks:
      - galaxy_net

  auth_service:
    image: auth_service_image
    env_file:
      - ./auth_service/.env
    build:
      context: ./auth_service
    ports:
      - "8001:8001"
    depends_on:
      - mongo_auth
    networks:
      - galaxy_net
#    deploy:
#      replicas: 2 #done for test of two services
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  questions_history_service:
    image: questions_history_service_image
    env_file:
      - ./questions_history/.env
    build:
      context: ./questions_history
    ports:
      - "8003:8003"
    depends_on:
      - question_history_db
    networks:
      - galaxy_net
    #    deploy:
    #      replicas: 2 #done for test of two services
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8001/health" ]
      interval: 30s
      timeout: 10s
      retries: 3

  question_service:
    image: question_service_image
    env_file:
      - ./question_service/.env
    build:
      context: ./question_service
    ports:
      - "8002:8002"
    networks:
      - galaxy_net
    depends_on:
      - questions_db

  questions_db:
    image: postgres:15
    container_name: questions_db
    restart: always
    environment:
      POSTGRES_USER: ${QUESTIONS_DB_USER}
      POSTGRES_PASSWORD: ${QUESTIONS_DB_PASSWORD}
      POSTGRES_DB: ${QUESTIONS_DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - galaxy_net

  mongo_auth:
    image: mongo:latest
    container_name: mongo_auth
    ports:
      - "27017:27017"
    volumes:
      - mongo_auth_data:/data/db
    networks:
      - galaxy_net

  question_history_db:
    image: mongo:latest
    container_name: mongo_question_history
    ports:
      - "27019:27019"
    volumes:
      - mongo_question_history_data:/data/db
    networks:
      - galaxy_net

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "3000:80"
    depends_on:
      - gateway
    networks:
      - galaxy_net

#  rabbitmq:
#    image: "rabbitmq:3-management"
#    container_name: rabbitmq
#    ports:
#      - "5672:5672"
#      - "15672:15672"
#    environment:
#      RABBITMQ_DEFAULT_USER: admin
#      RABBITMQ_DEFAULT_PASS: admin


networks:
  galaxy_net:
    driver: bridge


volumes:
  mongo_question_history_data:
  mongo_auth_data:
  postgres_data:
